source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

target 'WCoreKit_Example' do
  pod "WCoreKit", :path => "../"
end

#target 'WCoreKit_Tests', :exclusive => true do
#  pod "WCoreKit", :path => "../"
#
#  pod 'FBSnapshotTestCase'
#end
